custom: 
  - "Bitcoin: bc1qlyt7pw3d0az09g7m9dyn8t6jc3j4crjclcx3fg"


please fund mee i software will always be free but pls fund me im sving up for better stuff to build on so i can keep making stuff
for yall thanks!! u dont have to tho
